version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: sa
      POSTGRES_USER: sa
      POSTGRES_DB: test


  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080